# Instruct Travis to build PRs ass well as merges
# to master. See https://stackoverflow.com/a/31882307/145400.
branches:
  only:
    - master

os:
  - linux
#  - osx

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install .
  - pip install -r requirements-tests.txt

script:
    - python --version
    - uname -a
    - pytest -vv test/
    - bash audit.sh
