os:
  - linux
#  - osx

language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"

install:
  - pip install .
  - pip install -r requirements-tests.txt

script:
    - python --version
    - uname -a
    - pytest -vv test/
