name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-18.04, macos-10.15, windows-latest]
        gevent-version-spec: ["gevent==1.5.0"]
        exclude:
          # see https://github.com/jgehrcke/gipc/issues/100
          - os: macos-10.15
            python-version: 3.8

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies on macOS
        if: startsWith(matrix.os, 'macos')
        # For the `gtimeout` command
        run: |
          brew install coreutils
      - name: Prepare CI environment
        env:
          GEVENT_VERSION: ${{ matrix.gevent-version-spec }}
        run: |
          bash ci/prepare-ci-env.sh
          python --version && uname -a
          pip list
      - name: pytest
        run: |
          pytest -vv test/
      - name: examples
        run: |
          bash examples/run-all.sh
      - name: audit
        run: |
          bash ci/audit.sh
